site_name: 'Codiac'
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - CLI Documentation
    - './cli'
    - 'command0-reference.md'
  - 'Api Platform'
    - Intro: './api-base/index.md'
    - 'Getting Started': 'getting-started'
    - Concepts: 
    - Plugins: 
      - './mongodb-repo-plugin.md'