site_name: 'Codiac'
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - 'About Codiac': 
    - 'Introduction': './about/index.md'
    - 'Asset Development': './about/asset-dev.md'
    - 'DevOps Pipelines': './about/devops.md'
    - 'Runtime Management / Kubernetes': './about/runtime-mgmt.md'
  - 'Codiac CLI': 
    - Intro: './cli/index.md'
    - 'Installation': './cli/index.md#installation'
    - 'Getting Started / Tutorials': './cli/tutorials/index.md'
    - 'Command Reference': './cli/command-reference.md'
  - 'Build APIs': 
    - Intro: './api-base/index.md'
    - 'Getting Started / Tutorials': './api-base/getting-started/index.md'
    - 'Basics: Architecture and Components':
      - Intro: './api-base/basics/index.md'
      - 'custom-endpoints': './custom-endpoints.md'
      - 'StringFilter': './StringFilter.md'
      - 'custom-filter-defs': './custom-filter-defs.md'
      - 'repo-registry-pattern': './repo-registry-pattern.md'
      - 'patch-and-update': './patch-and-update.md'
      - 'custom-validation': './custom-validation.md'
      - 'using-ioc': './using-ioc.md'
    - 'Plugins': './api-base/plugins/index.md'
    