site_name: 'Codiac'
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - 'Api Platform': './api-base/index.md'
    - 'Getting Started': './api-base/getting-started/README.md'
  - 'CLI Documentation': './cli/index.md'
    - './cli/command-reference.md'
