site_name: 'Codiac'
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - 'About Codiac': './about/index.md'
    - 'Introduction': './about/index.md'
    - 'Asset Development': './about/asset-dev.md'
    - 'DevOps Pipelines': './about/devops.md'
    - 'Runtime Management / Kubernetes': './about/runtime-mgmt.md'
  - 'Codiac CLI': './cli/index.md'
    - 'Installation': './cli/index.md#installation'
    - 'Getting Started / Tutorials': './cli/tutorials/index.md'
    - 'Command Reference': './cli/command-reference.md'
  - 'Build APIs': './api-base/index.md'
    - 'Getting Started / Tutorials': './api-base/getting-started/index.md'
    - 'Basics: Architecture and Components': './api-base/basics/index.md'
    - 'Plugins': './api-base/plugins/index.md'
    