site_name: 'Codiac'
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - 'CLI Documentation':
    - Intro: './cli/index.md'
    - './cli/command-reference.md'
  - 'Api Platform': './api-base/index.md'
    - 'Getting Started': './api-base/getting-started'
    - Plugins: 
      - './api-base/mongodb-repo-plugin.md'
